$( function() {
$('#list420').click(function() {$('#topic90 span.listtxt').html('我听过的最好听的版本，陈明太有感觉了！');$('#topic90 embed').wrap('<div class="videoWrapper" />');$('#topic90 embed').replaceWith('<embed src="http://player.youku.com/player.php/sid/XNTA5OTQxNDAw/v.swf" quality="high" width="680" height="480" align="middle" allowScriptAccess="sameDomain" allowFullscreen="true" type="application/x-shockwave-flash"></embed>');$('#topic90 li').css('color', '#000000');$('#list420').css('color', '#CC0052');});
$('#list421').click(function() {$('#topic90 span.listtxt').html('我一直很喜欢这首歌，杨宗纬唱得很好听。');$('#topic90 embed').wrap('<div class="videoWrapper" />');$('#topic90 embed').replaceWith('<embed src="http://player.youku.com/player.php/sid/XNTA5OTU2MDQ4/v.swf" quality="high" width="680" height="480" align="middle" allowScriptAccess="sameDomain" allowFullscreen="true" type="application/x-shockwave-flash"></embed>');$('#topic90 li').css('color', '#000000');$('#list421').css('color', '#CC0052');});
$('#list422').click(function() {$('#topic90 span.listtxt').html('羽泉唱的歌很是煽情啊，太会挑歌了。');$('#topic90 embed').wrap('<div class="videoWrapper" />');$('#topic90 embed').replaceWith('<embed src="http://player.youku.com/player.php/sid/XNTA5OTMzODA4/v.swf" quality="high" width="680" height="480" align="middle" allowScriptAccess="sameDomain" allowFullscreen="true" type="application/x-shockwave-flash"></embed>');$('#topic90 li').css('color', '#000000');$('#list422').css('color', '#CC0052');});
$('#list423').click(function() {$('#topic90 span.listtxt').html('我从未听过这首歌，唱得确实好。');$('#topic90 embed').wrap('<div class="videoWrapper" />');$('#topic90 embed').replaceWith('<embed src="http://player.youku.com/player.php/sid/XNTA2ODgwNTQ4/v.swf" quality="high" width="680" height="480" align="middle" allowScriptAccess="sameDomain" allowFullscreen="true" type="application/x-shockwave-flash"></embed>');$('#topic90 li').css('color', '#000000');$('#list423').css('color', '#CC0052');});
$('#list424').click(function() {$('#topic90 span.listtxt').html('太感动了啊');$('#topic90 embed').wrap('<div class="videoWrapper" />');$('#topic90 embed').replaceWith('<embed src="http://player.youku.com/player.php/sid/XNTA2OTAzMzMy/v.swf" quality="high" width="680" height="480" align="middle" allowScriptAccess="sameDomain" allowFullscreen="true" type="application/x-shockwave-flash"></embed>');$('#topic90 li').css('color', '#000000');$('#list424').css('color', '#CC0052');});
$('#list430').click(function() {$('#topic90 span.listtxt').html('羽凡开头那两声太牛X了！');$('#topic90 embed').wrap('<div class="videoWrapper" />');$('#topic90 embed').replaceWith('<embed src="http://player.yinyuetai.com/video/player/604297/v_0.swf" quality="high" width="680" height="480" align="middle"  allowScriptAccess="sameDomain" allowfullscreen="true" type="application/x-shockwave-flash"></embed>');$('#topic90 li').css('color', '#000000');$('#list430').css('color', '#CC0052');});
$('#list431').click(function() {$('#topic90 span.listtxt').html('唱歌者心痛，听歌者心疼。');$('#topic90 embed').wrap('<div class="videoWrapper" />');$('#topic90 embed').replaceWith('<embed src="http://player.youku.com/player.php/sid/XNTEyNjgwMDI0/v.swf" quality="high" width="680" height="480" align="middle" allowScriptAccess="sameDomain" allowFullscreen="true" type="application/x-shockwave-flash"></embed>');$('#topic90 li').css('color', '#000000');$('#list431').css('color', '#CC0052');});
$('#list432').click(function() {$('#topic90 span.listtxt').html('唱得多好，居然把杨宗纬淘汰了！');$('#topic90 embed').wrap('<div class="videoWrapper" />');$('#topic90 embed').replaceWith('<embed src="http://player.yinyuetai.com/video/player/604298/v_0.swf" quality="high" width="680" height="480" align="middle"  allowScriptAccess="sameDomain" allowfullscreen="true" type="application/x-shockwave-flash"></embed>');$('#topic90 li').css('color', '#000000');$('#list432').css('color', '#CC0052');});
$('#list434').click(function() {$('#topic90 span.listtxt').html('有点想哭的感觉');$('#topic90 embed').wrap('<div class="videoWrapper" />');$('#topic90 embed').replaceWith('<embed src="http://player.yinyuetai.com/video/player/605801/v_0.swf" quality="high" width="680" height="480" align="middle"  allowScriptAccess="sameDomain" allowfullscreen="true" type="application/x-shockwave-flash"></embed>');$('#topic90 li').css('color', '#000000');$('#list434').css('color', '#CC0052');});
$('#list435').click(function() {$('#topic90 span.listtxt').html('厉害，喜欢。');$('#topic90 embed').wrap('<div class="videoWrapper" />');$('#topic90 embed').replaceWith('<embed src="http://player.yinyuetai.com/video/player/605820/v_0.swf" quality="high" width="680" height="480" align="middle"  allowScriptAccess="sameDomain" allowfullscreen="true" type="application/x-shockwave-flash"></embed>');$('#topic90 li').css('color', '#000000');$('#list435').css('color', '#CC0052');});
$('#list436').click(function() {$('#topic90 span.listtxt').html('好哀怨凄美的爱情故事，“我听闻，你始终一个人...”');$('#topic90 embed').wrap('<div class="videoWrapper" />');$('#topic90 embed').replaceWith('<embed src="http://player.yinyuetai.com/video/player/612711/v_0.swf" quality="high" width="680" height="480" align="middle"  allowScriptAccess="sameDomain" allowfullscreen="true" type="application/x-shockwave-flash"></embed>');$('#topic90 li').css('color', '#000000');$('#list436').css('color', '#CC0052');});
$('#list437').click(function() {$('#topic90 span.listtxt').html('原来不太习惯她的唱法，不过这首确实很霸气啊。');$('#topic90 embed').wrap('<div class="videoWrapper" />');$('#topic90 embed').replaceWith('<embed src="http://player.yinyuetai.com/video/player/612708/v_0.swf" quality="high" width="680" height="480" align="middle"  allowScriptAccess="sameDomain" allowfullscreen="true" type="application/x-shockwave-flash"></embed>');$('#topic90 li').css('color', '#000000');$('#list437').css('color', '#CC0052');});
$('#list439').click(function() {$('#topic90 span.listtxt').html('好听，感动～');$('#topic90 embed').wrap('<div class="videoWrapper" />');$('#topic90 embed').replaceWith('<embed src="http://player.yinyuetai.com/video/player/618472/v_0.swf" quality="high" width="680" height="480" align="middle"  allowScriptAccess="sameDomain" allowfullscreen="true" type="application/x-shockwave-flash"></embed>');$('#topic90 li').css('color', '#000000');$('#list439').css('color', '#CC0052');});
$('#list440').click(function() {$('#topic90 span.listtxt').html('很喜欢林志炫啊，天籁之音～～～');$('#topic90 embed').wrap('<div class="videoWrapper" />');$('#topic90 embed').replaceWith('<embed src="http://player.yinyuetai.com/video/player/618469/v_0.swf" quality="high" width="680" height="480" align="middle"  allowScriptAccess="sameDomain" allowfullscreen="true" type="application/x-shockwave-flash"></embed>');$('#topic90 li').css('color', '#000000');$('#list440').css('color', '#CC0052');});
});
